### PR TITLE
Fix insert-opener

### LINKED ISSUE #2: Doesn't work in mac
After entering `:auto-pairs-enable` command, I expect auto pair completion, but nothing happens.
For example I enter `{` and result is the same.
I'm using mac os kakoune version.

### PR DESCRIPTION
**Pull request by topisani**
This closes #2

### CODE REVIEW

**Comment by maximbaz** [comment]
@alexherbo2 please merge.

**Comment by maximbaz** [comment]
@alexherbo2 this can be closed now too :)

**Comment by alexherbo2** [comment]
@maximbaz I wanted to close it with the commit, but it didn’t work.

**Comment by maximbaz** [comment]
Yeah I've seen, you have to repeat "fixes" for every issue 🙂

**Pull request closed without merging**
