### PR TITLE
remove kakoune.cr dependency

### PR DESCRIPTION
**Pull request by dead10ck**
I took a crack at #49 and I was able to get something working. I also fixed the case where there were no saved pairs, which was generating incomplete and invalid commands.

### CODE REVIEW

**Comment by dead10ck** [comment]
@alexherbo2 any thoughts?

**Comment by CBenoit** [comment]
I suggest to also update README.md and replace `kakoune.rc` requirement by `jq`

**Comment by dead10ck** [comment]
I'd be happy to, but I'm not sure if @alexherbo2 is interested in merging this.

**Comment by crocket** [comment]
This pull request works. I use this pull request with
```
plug "dead10ck/auto-pairs.kak" branch "remove-kcr" demand auto-pairs %{
  auto-pairs-enable
}
```

**Comment by kkga** [comment]
Yes, it works great. I've been using it for a while, since setting up proper PATH to `kcr` can be sometimes tricky on macOS. Thanks @dead10ck 👍

@alexherbo2 Any chance this could be merged?

**Comment by ScratchX98** [comment]
I love you man, works amazing

**Comment by alexherbo2** [comment]
Done

**Pull request closed without merging**
